repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.12
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.0
    hooks:
      - id: commitizen
