name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow==2.12.0 efficientnet==1.1.1 torch==2.4.1 ultralytics==8.3.26 tflite-runtime==2.12.0
          pip install -e .

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*.py'
